import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { FormEvent, useEffect, useRef, useState } from "react";
import Randomiser from "@/components/Randomiser";
import Search from "@/components/Search";
import { BasicGame, User } from "@types";

export default function Home() {
  const [games, setGames] = useState<BasicGame[] | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [mode, setMode] = useState<"search" | "randomiser">("search");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {mode === "search" && (
          <Search setMode={setMode} setGames={setGames} setUser={setUser} />
        )}

        {mode === "randomiser" && user && games ? (
          <Randomiser setMode={setMode} user={user} games={games} />
        ) : null}
      </main>

      {/* <footer></footer> */}
    </>
  );
}
